# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: buildandtest
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          npm install -g @quasar/cli
          npm install
          quasar build
        env:
          VUE_API_ENDPOINT: "$(VUE_API_ENDPOINT)"
          VUE_ROUTER_MODE: "history"
        workingDirectory: "$(Build.SourcesDirectory)"
        displayName: "install Quasar CLI and build app"
      - task: CopyFiles@2
        inputs:
          Contents: "dist/spa/**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"

      - task: AzureStaticWebApp@0
        inputs:
          workingDirectory: "$(Build.ArtifactStagingDirectory)"
          app_location: "dist/spa/"
          is_static_export: true
          azure_static_web_apps_api_token: "95e29ac6902f77d67002bbe8c28421c09cc28609e841bd5fc4c10a58882ba7ff4-40cab8d9-1d0b-4a73-b06e-e0f546306566010285191"
          production_branch: "master"
